# Default values for otus-java-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: shkodinda/otus-docker-lesson

service:
  type: NodePort
  port: 8000

ingress:
  host: arch.homework

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: "1"
  postgresqlDatabase: users_db
  service:
    port: 5432

#ingress:
#  enabled: false
#  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  #hosts:
  #  - host: chart-example.local
  #    paths: []
 # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


tolerations: []

affinity: {}
