apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: java-app-secret
data:
  DB_PASSWORD: MQ==
  DB_NAME: dXNlcnNfZGI=
  DB_USERNAME: cG9zdGdyZXM=


