apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                    key: DB_NAME
                    name: java-app-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                    key: DB_USERNAME
                    name: java-app-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                    key: DB_PASSWORD
                    name: java-app-secret
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi