apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-config
data:
  DB_HOST: {{ printf "%s" (include "postgresql.fullname" .)}}
  DB_PORT: {{ printf "%s" .Values.postgresql.service.port}}

---
apiVersion: v1
kind: Secret
metadata:
  name: java-app-secret
data:
  DB_PASSWORD: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_NAME: {{ printf "%s" .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_USERNAME: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}

