apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otus-java-app-chart.fullname" . }}
data:
  DB_HOST: "{{ (include "postgresql.fullname" .) }}"
  DB_PORT: "{{ .Values.postgresql.service.port }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otus-java-app-chart.fullname" . }}
data:
  DB_PASSWORD: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_NAME: {{ printf "%s" .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_USERNAME: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}

